const typeFiqueLigado = {
  CONSTRUÇÃO: [
    "PE1 - CV1 - CONSTRUÇÃO VÍRTUA FIBRA",
    "PE1 - MD3 - ACOMPANHAMENTO CONSTRUCAO DE MDU",
    "PE1 - MD7 - ACOMPANHAMENTO CONSTRUÇÃO MDU GPON",
  ],
  PRÉDIOS: [
    "PE1 - MD1 - PRÉDIO SEM BACK BONE",
    "PE1 - MD2 - PRÉDIO SEM RETORNO ATIVO",
    "PE1 - MD4 - ATUALIZACAO STATUS CONSTRUCAO MDU",
    "PE1 - MD8 - ATUALIZAÇÃO DE STATUS DE CONSTRUÇÃO MDU GPON",
  ],
  PROJETOS: [
    "PE1 - MD5 - PROJETO DE ADEQUACAO REDE EXTERNA MDU GPON",
    "PE1 - NP2 – PROJETO DE NAP",
    "PE1 - TP2 – PROJETO DE TAP",
    "PE1 - NP5 – REVISÃO DE TRATAMENTO",
  ],
  REDES: [
    "PE1 - NP1 - NAP LOTADO",
    "PE1 - NP3 - EM EXECUCAO DE ADEQUACAO DE REDE",
    "PE1 - NP4 - ADEQUAÇÃO DE CADASTRO",
    "PE1 - OP1 - EXECUCAO DE ADEQUACAO EM REDE OPTICA",
    "PE1 - RU1 - RUA NÃO CABEADA",
    "PE1 - RU3 – RUA NÃO CABEADA GPON",
  ],
  MANUTENÇÃO: [
    "PE1 - MD11 - SAR MANUTENCAO MDU",
    "PE1 - TP1 - FALTA TAP / TAP LOTADO",
    "PE1 - TP3 – EM EXECUÇÃO DE ADEQUAÇÃO DE REDE",
  ],
  VISTORIAS: [
    "PE1 - VT1 – VISTORIA EM CAMPO",
    "PE1 - VT2 – NECESSIDADE DE VISTORIA EM MDU",
    "PE1 - VT3 – NECESSIDADE DE VISTORIA TAP",
  ],
};

export default typeFiqueLigado;
